In [1]:
import numpy as np

In [2]:
list_input =  [1,2,3,4,5]
np_list = np.array(list_input)
print(np_list)

[1 2 3 4 5]


In [3]:
print(type(np_list))

<class 'numpy.ndarray'>


In [4]:
list_2D = [[1,2,3],[4,5,6]]
np_list2D = np.array(list_2D)

In [5]:
print(np_list2D.shape)

(2, 3)


In [6]:
multiplicator_factor = np.array([2,3,1])

In [7]:
print(np_list2D * multiplicator_factor)

[[ 2  6  3]
 [ 8 15  6]]


In [8]:
print(np.mean(np_list2D[0,:]))

2.0


In [9]:
print(np.mean(np_list2D[1,:]))

5.0


In [10]:
print(np.median(np_list2D[0,:]))

2.0


In [11]:
height = np.round(np.random.normal(1.75,0.20,5000),2)
weight = np.round(np.random.normal(60,0.20,5000),2)

In [12]:
height

array([1.75, 1.66, 1.43, ..., 1.65, 2.03, 1.55])

In [14]:
#standard deviation
print(np.std(height))

0.20351450502605456


In [15]:
# sum
print(np.sum(height))

8749.19


In [17]:
# sort
print(np.sort(height))

[1.01 1.03 1.06 ... 2.38 2.44 2.52]


In [18]:
#column_stack to change row items into columns
print(np.column_stack(np_list2D))

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#correlation coefficient
print(np.corrcoef())